import './global.css';
import type { Metadata } from 'next';
import { css } from '@/styled-system/css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// FIXME: https://typescript-eslint.io/rules/prefer-readonly-parameter-types/
// eslint-disable-next-line @typescript-eslint/prefer-readonly-parameter-types
const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={css({ paddingX: '24px' })}>
      <header>
        <h1 className={css({ fontSize: '2rem', fontWeight: 'bold' })}>
          review-pull-request
        </h1>
      </header>
      <article>{children}</article>
    </body>
  </html>
);

export default RootLayout;
